[package]
name = "rustpg"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.8"
serde = { version = "1.0.215", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio"] }
dotenv = "0.15"  
